### ISSUE TITLE
How to capture 1 frame?

### ISSUE THREAD

**Issue by Youdiie** [paulkre/bevy_image_export#2]
Hello, I want to render just one particular frame using bevy_image_export.
However, in this issue(https://github.com/paulkre/bevy_image_export/issues/1) there is only a way to start and stop capturing.
Any hint is welcome!

**Comment by paulkre** [comment]
Hi, if you just want to export a single frame you might be better of using Bevy’s internal [`ScreenshotManager`](https://bevyengine.org/news/bevy-0-11/#screenshot-api). Otherwise you would have to spawn an `ImageExportBundle` and then immediately despawn it in the subsequent frame.

**Comment by Youdiie** [comment]
Thanks for replying!
I used Bevy's `ScreenshotManager`, but I couldn't resize the result :(
Also I wrote the code to an ImageExportBundle and then immediately despawn it in the subsequent frame, but  `save_buffer_to_disk()` didn't stop. Is there any way?

**Comment by paulkre** [comment]
So you’re saying, `ImageExportBundle` kept on exporting frames, even after you despawned the entity? Could you please send me the code of the systems you used?

**Comment by Youdiie** [comment]
Oh, I'm sorry. I made a mistake.
After I despawned, it crashed like this:
```
thread 'Compute Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: NoEntities("bevy_ecs::query::state::QueryState<bevy_ecs::entity::Entity, bevy_ecs::query::filter::With<...::render::ExportBundleMarker>>")'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `...::render::save_image`!
thread '<unnamed>' panicked at 'The TimeSender channel should always be empty during render. You might need to add the bevy::core::time_system to your app.: "Disconnected(..)"', ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.11.0/src/renderer/mod.rs:91:44
Encountered a panic in exclusive system `bevy_render::renderer::render_system`!
```
My code is here:
```
#[derive(Component)]
pub struct ExportBundleMarker;

pub fn save_image(
    mut commands: Commands,
    mut export_sources: ResMut<Assets<ImageExportSource>>,
    output_texture: ResMut<TextureHandle>,
    input: Res<Input<KeyCode>>,
    export_bundles: Query<Entity, With<ExportBundleMarker>>,
) {
    if input.just_pressed(KeyCode::Space) {
        commands.spawn((ImageExportBundle {
            source: export_sources.add(output_texture.texture.clone().into()),
            settings: ImageExportSettings {
                extension: "exr".into(),
                ..default()
            },
        },));

        // after render
        commands.entity(export_bundles.single()).despawn();
    }
}
```

So I tried to use resource to change state after spawn, but `save_buffer_to_disk()` is on sub_app so it can't use world resource 🥲

**Comment by paulkre** [comment]
The issue is that you are attempting to despawn the entity on the same frame you are spawning it on. You have to wait one iteration for Bevy to add the entity to the `Query` object (`export_bundles`). To address this, I made modifications to your code. Now, all entities with the `ExportBundleMarker` will be despawned on every frame. Consequently, the `ImageExportBundle` will exist for exactly one frame:

```rust
#[derive(Component)]
pub struct ExportBundleMarker;

pub fn save_image(
    mut commands: Commands,
    mut export_sources: ResMut<Assets<ImageExportSource>>,
    output_texture: ResMut<TextureHandle>,
    input: Res<Input<KeyCode>>,
    export_bundles: Query<Entity, With<ExportBundleMarker>>,
) {
    if input.just_pressed(KeyCode::Space) {
        commands.spawn((
            ImageExportBundle {
                source: export_sources.add(output_texture.texture.clone().into()),
                settings: ImageExportSettings {
                    extension: "exr".into(),
                    ..default()
                },
            },
            ExportBundleMarker,
        ));
    }

    for bundle in &export_bundles {
        commands.entity(bundle).despawn();
    }
}
```

You are currently exporting an HDR image (EXR), so please make sure to use `TextureFormat::Rgba32Float` as the format in your output texture’s image properties.

**Comment by paulkre** [comment]
On top of that, you forgot to add the `ExportBundleMarker` to the entity holding the `ImageExportBundle`.

**Comment by Youdiie** [comment]
Wow it works! Thank you for your kind explanation :)
And yes, I forgot to add `ExportBundleMarker` 😂
