### ISSUE TITLE
Export with transparent background?

### ISSUE THREAD

**Issue by jeertmans** [paulkre/bevy_image_export#4]
Hello, I was wondering if exporting with transparent background was supported?

Thanks :-)

**Comment by brandon-reinhart** [comment]
It appears to work fine.

**Comment by jeertmans** [comment]
Do you have an small working example @brandon-reinhart ?

**Comment by paulkre** [comment]
Hi @jeertmans, sorry for the late reply. In order to export images with transparent backgrounds you have to set the `clear_color` property of the `Camera3d`/`Camera2d` component that you use for rendering the image sequence. This would be an example:

```rust
commands.spawn(Camera3dBundle {
    camera: Camera {
        target: RenderTarget::Image(output_texture),
        ..default()
    },
    camera_3d: Camera3d {
        clear_color: ClearColorConfig::Custom(Color::rgba(0.0, 0.0, 0.0, 0.0)),
        ..default()
    },
    ..default()
});
```

**Comment by jeertmans** [comment]
Thanks!
